# Generated by Django 5.2.4 on 2025-08-07 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_uploadedpdf_delete_uploadpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='api.chat'),
        ),
    ]
