# Generated by Django 5.2.4 on 2025-08-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_uploadedpdf_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_bot',
            field=models.CharField(choices=[('gpt', 'GPT'), ('gemini', 'Gemini')], default='gpt', max_length=10),
        ),
    ]
