POST http://localhost:8000/api/prompt_gpt/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1OTgyNDg2LCJpYXQiOjE3NTU5Nzg4ODYsImp0aSI6ImMxODhkMTUwMjllNjRjMDNhMjA0Nzc4Mjg3MDc4N2EyIiwidXNlcl9pZCI6IjE3In0.YyYsGPmS3ahpdRoTWUgKtRvIm4YK2YpVI7fdT9sunak

{
    "chat_id":"550e8400-e29b-41d4-a716-446655733200",
    "content":"How to make money"
}

###
POST http://localhost:8000/api/register/ HTTP/1.1
Content-Type: application/json

{
  "first_name": "don",
  "last_name":"cena",
  "email": "don@example.com",
  "password": "test1234",
  "confirm_password":"test1234"
}


###
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
  "email": "abrar_2022bite057@nitsri.ac.in",
  "password":"chips1234"
}

###
POST http://localhost:8000/api/improve/prompt/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1NTE4NTkxLCJpYXQiOjE3NTU1MTQ5OTEsImp0aSI6ImRhNmFhNjUxZjA0YTQ0M2I4ZWNjNjRhYzNlM2IwMzI5IiwidXNlcl9pZCI6IjE3In0.fjo2T-M4g4OfJA4xqd4PGA7N1XueZzt4QgaC0QMzgXA

{
  "message":"How to make chai"
}


###

DELETE http://localhost:8000/api/chat/delete/556e8402-e29b-41d4-a715-449659460810/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0MTQ3Nzc5LCJpYXQiOjE3NTQxNDU5NzksImp0aSI6ImI3MWEzMjlhMGMwMTRlYjI5Y2Q0YWEwOTFmZWFjYjQ5IiwidXNlcl9pZCI6IjE0In0.kE7jTx--KX2wG2ZOKsjL8_XrveU732MRjQTioeLZh1M

###
GET http://localhost:8000/api/chat/history/556e8402-e29b-41d4-a715-776766698777/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0MTYxMzI3LCJpYXQiOjE3NTQxNTk1MjcsImp0aSI6ImMxNzE2NTI5MDBkMzQ1NzdiMmEzZTZkZWY5Mjg4NzhkIiwidXNlcl9pZCI6IjE0In0.E3dya_nGsYfmljEUSM2cQKz1GWZMeudL54qzusGQkPs

###
POST http://localhost:8000/api/pdfs/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0NTkwMzY1LCJpYXQiOjE3NTQ1ODY3NjUsImp0aSI6ImUzMDRiZDQwNjljNTQ0Mjc5NjgwNjFjMDczNmZjNjZiIiwidXNlcl9pZCI6IjE0In0.8hnat38a1hJWL3nbM3OrGBISc0b7dG8la3dpUsJnTpY
Content-Type: multipart/form-data
###
POST http://localhost:8000/api/choose/model/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2MDY3MzAyLCJpYXQiOjE3NTYwNjM3MDIsImp0aSI6ImY4OWQ0YjQzZjBjNjQ0MjNiMGM4YmNjM2EwYzIxZWNkIiwidXNlcl9pZCI6IjE0In0.ISXsGjtw7wpFR1V0f_xmpr1rgRk9kGvA_iusoNPVn5I
Content-Type: application/json

{
  "choice":"gemini"
}